# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Test

# This workflow only runs linter, builds and runs unit tests for development branches.

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - '!main'
    paths-ignore:
      - 'docs/**'  
  pull_request:
    branches:
      - '**'
      - '!main'

jobs:

  build:
    name: Build and test project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    
    - name: Preparing
      run: sudo apt-get -y install libvpx-dev

    - name: Linting
      run: |
        cd backend
        go fmt ./...
        go vet ./...

    - name: Test
      run: cd backend && go test -v ./...
    
    - name: Build
      run: cd backend && go build -v ./...
